name: Publish RubyGems package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - run: bundle install
      - name: publish gem
        env:
          # ruleid: rubygems-publish-key
          GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_AUTH_TOKEN }}"
        run: |
          gem build *.gemspec
          gem push *.gem
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        # ok: rubygems-publish-key
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@v1
